version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    command: poetry run uvicorn main:app --host 0.0.0.0
    ports:
      - "8000:8000"
    platform: linux/amd64
    image: 11thbackend/web:latest
    env_file:
      - .env
    depends_on:
      - redis
  beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_config.celery_app.celery_task beat --loglevel=info
    depends_on:
      - redis
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A celery_config.celery_app.celery_task worker --loglevel=info
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
        - "6379:6379"
