version: '3'
services:
  web:
    image: 279381197488.dkr.ecr.ap-northeast-2.amazonaws.com/notion-slack-web:latest
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /project/src
    command: uvicorn main:app --host 0.0.0.0
    ports:
      - "8000:8000"
    platform: linux/amd64
    env_file:
      - .env
    networks:
      - mynetwork
  beat:
    image: 279381197488.dkr.ecr.ap-northeast-2.amazonaws.com/notion-slack-beat:latest
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /project/src
    command: celery -A celery_config.celery_app.celery_task beat --loglevel=info
    platform: linux/amd64
    env_file:
      - .env
    networks:
      - mynetwork
  worker:
    image: 279381197488.dkr.ecr.ap-northeast-2.amazonaws.com/notion-slack-worker:latest
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /project/src
    command: celery -A celery_config.celery_app.celery_task worker --loglevel=info
    platform: linux/amd64
    env_file:
      - .env
    networks:
      - mynetwork
  flower:
    image: 279381197488.dkr.ecr.ap-northeast-2.amazonaws.com/notion-slack-flower:latest
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /project/src
    command: celery -A celery_config.celery_app.celery_task flower
    platform: linux/amd64
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - worker 
      - beat
    networks:
      - mynetwork
networks:
  mynetwork:
    external: true