"""엔티티 생성

Revision ID: 09cd3627b310
Revises: 
Create Date: 2023-10-27 00:09:54.736407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09cd3627b310'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('notion_api_token', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slack_api_token', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notion_database',
    sa.Column('notion_database_id', sa.String(length=256), nullable=False),
    sa.Column('notion_id', sa.Integer(), nullable=True),
    sa.Column('db_name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['notion_id'], ['notion.id'], ),
    sa.PrimaryKeyConstraint('notion_database_id')
    )
    op.create_table('slack_channel',
    sa.Column('slack_channel_id', sa.String(length=256), nullable=False),
    sa.Column('slack_id', sa.Integer(), nullable=True),
    sa.Column('channel_name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['slack_id'], ['slack.id'], ),
    sa.PrimaryKeyConstraint('slack_channel_id')
    )
    op.create_table('notion_page',
    sa.Column('page_id', sa.String(length=128), nullable=False),
    sa.Column('notion_database_id', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Enum('CONFIRMED', 'CANCELLED', name='statuschoice'), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('meeting_type', sa.String(length=64), nullable=False),
    sa.Column('meeting_url', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['notion_database_id'], ['notion_database.notion_database_id'], ),
    sa.PrimaryKeyConstraint('page_id')
    )
    op.create_table('notion_slack_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notion_database_id', sa.String(length=256), nullable=True),
    sa.Column('slack_channel_id', sa.String(length=256), nullable=True),
    sa.Column('connect_name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['notion_database_id'], ['notion_database.notion_database_id'], ),
    sa.ForeignKeyConstraint(['slack_channel_id'], ['slack_channel.slack_channel_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notion_slack_mapping')
    op.drop_table('notion_page')
    op.drop_table('slack_channel')
    op.drop_table('notion_database')
    op.drop_table('slack')
    op.drop_table('notion')
    # ### end Alembic commands ###
