"""참여자추가

Revision ID: 2b5a43df533a
Revises: 09cd3627b310
Create Date: 2023-10-28 00:26:59.939873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b5a43df533a'
down_revision: Union[str, None] = '09cd3627b310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notion_page', sa.Column('participants', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notion_page', 'participants')
    # ### end Alembic commands ###
