"""empty message

Revision ID: 443ccd921022
Revises: a3b07b1c17ed
Create Date: 2023-09-19 20:50:05.150388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '443ccd921022'
down_revision: Union[str, None] = 'a3b07b1c17ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'CANCELLED', name='statuschoice'), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('meeting_type', sa.String(length=64), nullable=False),
    sa.Column('meeting_url', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notion')
    # ### end Alembic commands ###
