"""empty message

Revision ID: 536f81220df6
Revises: 
Create Date: 2023-09-22 17:23:28.961784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '536f81220df6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notion',
    sa.Column('page_id', sa.String(length=128), nullable=False),
    sa.Column('notion_database_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'CANCELLED', name='statuschoice'), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('meeting_type', sa.String(length=64), nullable=False),
    sa.Column('meeting_url', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('page_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notion')
    # ### end Alembic commands ###
