"""empty message

Revision ID: 87b1eb8d52a7
Revises: 536f81220df6
Create Date: 2023-09-26 13:31:50.612707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87b1eb8d52a7'
down_revision: Union[str, None] = '536f81220df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notionslackmapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notion_database_id', sa.String(length=128), nullable=False),
    sa.Column('slack_channel_id', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notionslackmapping')
    # ### end Alembic commands ###
