"""empty message

Revision ID: d4b6df660d65
Revises: 75d0eb45571e
Create Date: 2023-09-20 10:22:41.072797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4b6df660d65'
down_revision: Union[str, None] = '75d0eb45571e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notion',
    sa.Column('page_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'CANCELLED', name='statuschoice'), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('meeting_type', sa.String(length=64), nullable=False),
    sa.Column('meeting_url', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('page_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notion')
    # ### end Alembic commands ###
